export enum ConfigKey {
  PROJECT_NAME = 'PROJECT_NAME',
  PROJECT_DOMAIN = 'PROJECT_DOMAIN',
  DATABASE_URL = 'DATABASE_URL',
  JWT_SECRET = 'JWT_SECRET',
  SALT_SECRET = 'SALT_SECRET',
  SERVER_PORT_HTTP = 'SERVER_PORT_HTTP',
  SERVER_PORT_HTTPS = 'SERVER_PORT_HTTPS',
}
